name: Lyrical Build master
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '13 4 * * *'

jobs:
  lyrical_binary_master:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: lyrical
      ros_repo: master
      upstream_workspace: 'repos.list'
      ref_for_scheduled_build: master
      before_install_upstream_dependencies: 'sudo apt install -y libboost-regex-dev'
      image: 'ubuntu-26.04'